/**
 * Lista de chaves proibidas — nenhuma variação dessas chaves pode aparecer no payload.
 * A comparação é normalizada (sem separadores, lowercase) para detectar camelCase,
 * snake_case e kebab-case.
 */
export const PROHIBITED_KEYS_RAW: readonly string[] = [
  'value',
  'text',
  'cpf',
  'cnpj',
  'email',
  'phone',
  'telefone',
  'celular',
  'password',
  'senha',
  'pwd',
  'pass',
  'name',
  'nome',
  'sobrenome',
  'fullname',
  'full_name',
  'username',
  'usuario',
  'placa',
  'plate',
  'chassi',
  'chassis',
  'renavam',
  'vin',
  'numero_motor',
  'address',
  'endereco',
  'rua',
  'logradouro',
  'cidade',
  'city',
  'estado',
  'state',
  'cep',
  'zipcode',
  'zip',
  'bairro',
  'district',
  'latitude',
  'longitude',
  'lat',
  'lng',
  'location',
  'coords',
  'geopoint',
  'token',
  'jwt',
  'bearer',
  'access_token',
  'refresh_token',
  'expoPushToken',
  'push_token',
  'device_id',
  'advertising_id',
  'idfa',
  'gaid',
  'android_id',
  'fingerprint',
  'imei',
  'device_fingerprint',
  'user_id',
  'userId',
  'associado_id',
  'url',
  'uri',
  'src',
  'href',
  'title',
  'label',
  'filename',
  'file_name',
  'photo',
  'image',
  'imagem',
  'foto',
  'base64',
  'blob',
  'file',
  'document',
  'documento',
  'qrcode',
  'qr_code',
  'barcode',
  'cpf_hash',
  'email_hash',
  'phone_hash',
  'placa_hash',
  'user_hash',
  'hashed_cpf',
  'hashed_email',
];

/** Conjunto normalizado para lookup O(1). */
export const PROHIBITED_KEYS_NORMALIZED: ReadonlySet<string> = new Set(
  PROHIBITED_KEYS_RAW.map(normalizeKey),
);

/** Remove separadores e converte para lowercase para comparação uniforme. */
export function normalizeKey(key: string): string {
  return key.toLowerCase().replace(/[_\-\s]/g, '');
}
